// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/acm/cata.proto

package omo_msp_acm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CatalogInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Key                  string   `protobuf:"bytes,9,opt,name=key,proto3" json:"key,omitempty"`
	Type                 uint32   `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	Concepts             []string `protobuf:"bytes,21,rep,name=concepts,proto3" json:"concepts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CatalogInfo) Reset()         { *m = CatalogInfo{} }
func (m *CatalogInfo) String() string { return proto.CompactTextString(m) }
func (*CatalogInfo) ProtoMessage()    {}
func (*CatalogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a9106ab272e9d7, []int{0}
}

func (m *CatalogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CatalogInfo.Unmarshal(m, b)
}
func (m *CatalogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CatalogInfo.Marshal(b, m, deterministic)
}
func (m *CatalogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogInfo.Merge(m, src)
}
func (m *CatalogInfo) XXX_Size() int {
	return xxx_messageInfo_CatalogInfo.Size(m)
}
func (m *CatalogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogInfo proto.InternalMessageInfo

func (m *CatalogInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CatalogInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CatalogInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CatalogInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *CatalogInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CatalogInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *CatalogInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CatalogInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CatalogInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CatalogInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CatalogInfo) GetConcepts() []string {
	if m != nil {
		return m.Concepts
	}
	return nil
}

type ReqCatalogAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCatalogAdd) Reset()         { *m = ReqCatalogAdd{} }
func (m *ReqCatalogAdd) String() string { return proto.CompactTextString(m) }
func (*ReqCatalogAdd) ProtoMessage()    {}
func (*ReqCatalogAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a9106ab272e9d7, []int{1}
}

func (m *ReqCatalogAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCatalogAdd.Unmarshal(m, b)
}
func (m *ReqCatalogAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCatalogAdd.Marshal(b, m, deterministic)
}
func (m *ReqCatalogAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCatalogAdd.Merge(m, src)
}
func (m *ReqCatalogAdd) XXX_Size() int {
	return xxx_messageInfo_ReqCatalogAdd.Size(m)
}
func (m *ReqCatalogAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCatalogAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCatalogAdd proto.InternalMessageInfo

func (m *ReqCatalogAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCatalogAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCatalogAdd) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqCatalogAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCatalogAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReplyCatalogInfo struct {
	Info                 *CatalogInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyCatalogInfo) Reset()         { *m = ReplyCatalogInfo{} }
func (m *ReplyCatalogInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyCatalogInfo) ProtoMessage()    {}
func (*ReplyCatalogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a9106ab272e9d7, []int{2}
}

func (m *ReplyCatalogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCatalogInfo.Unmarshal(m, b)
}
func (m *ReplyCatalogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCatalogInfo.Marshal(b, m, deterministic)
}
func (m *ReplyCatalogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCatalogInfo.Merge(m, src)
}
func (m *ReplyCatalogInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyCatalogInfo.Size(m)
}
func (m *ReplyCatalogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCatalogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCatalogInfo proto.InternalMessageInfo

func (m *ReplyCatalogInfo) GetInfo() *CatalogInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyCatalogInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyCatalogList struct {
	Number               int32          `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*CatalogInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyCatalogList) Reset()         { *m = ReplyCatalogList{} }
func (m *ReplyCatalogList) String() string { return proto.CompactTextString(m) }
func (*ReplyCatalogList) ProtoMessage()    {}
func (*ReplyCatalogList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a9106ab272e9d7, []int{3}
}

func (m *ReplyCatalogList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCatalogList.Unmarshal(m, b)
}
func (m *ReplyCatalogList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCatalogList.Marshal(b, m, deterministic)
}
func (m *ReplyCatalogList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCatalogList.Merge(m, src)
}
func (m *ReplyCatalogList) XXX_Size() int {
	return xxx_messageInfo_ReplyCatalogList.Size(m)
}
func (m *ReplyCatalogList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCatalogList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCatalogList proto.InternalMessageInfo

func (m *ReplyCatalogList) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyCatalogList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyCatalogList) GetList() []*CatalogInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqCatalogUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Concepts             []string `protobuf:"bytes,6,rep,name=concepts,proto3" json:"concepts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCatalogUpdate) Reset()         { *m = ReqCatalogUpdate{} }
func (m *ReqCatalogUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqCatalogUpdate) ProtoMessage()    {}
func (*ReqCatalogUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a9106ab272e9d7, []int{4}
}

func (m *ReqCatalogUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCatalogUpdate.Unmarshal(m, b)
}
func (m *ReqCatalogUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCatalogUpdate.Marshal(b, m, deterministic)
}
func (m *ReqCatalogUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCatalogUpdate.Merge(m, src)
}
func (m *ReqCatalogUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqCatalogUpdate.Size(m)
}
func (m *ReqCatalogUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCatalogUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCatalogUpdate proto.InternalMessageInfo

func (m *ReqCatalogUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqCatalogUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCatalogUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCatalogUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCatalogUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqCatalogUpdate) GetConcepts() []string {
	if m != nil {
		return m.Concepts
	}
	return nil
}

func init() {
	proto.RegisterType((*CatalogInfo)(nil), "omo.msp.acm.CatalogInfo")
	proto.RegisterType((*ReqCatalogAdd)(nil), "omo.msp.acm.ReqCatalogAdd")
	proto.RegisterType((*ReplyCatalogInfo)(nil), "omo.msp.acm.ReplyCatalogInfo")
	proto.RegisterType((*ReplyCatalogList)(nil), "omo.msp.acm.ReplyCatalogList")
	proto.RegisterType((*ReqCatalogUpdate)(nil), "omo.msp.acm.ReqCatalogUpdate")
}

func init() {
	proto.RegisterFile("proto/acm/cata.proto", fileDescriptor_d4a9106ab272e9d7)
}

var fileDescriptor_d4a9106ab272e9d7 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6b, 0xdc, 0x30,
	0x10, 0x8d, 0x3f, 0xd6, 0x49, 0xb4, 0x24, 0x04, 0xd1, 0x6c, 0xc5, 0x42, 0xc0, 0xf8, 0xb4, 0x87,
	0xe2, 0x94, 0xf4, 0xd8, 0x43, 0xd9, 0x84, 0x52, 0x0a, 0x81, 0x16, 0x85, 0x5e, 0x7a, 0x09, 0x8a,
	0x3d, 0x09, 0x66, 0x2d, 0xcb, 0xb1, 0xe5, 0xc0, 0x1e, 0x7a, 0x2e, 0xf4, 0x27, 0xf4, 0x57, 0xf6,
	0x27, 0x14, 0x8d, 0x3f, 0x62, 0xef, 0xba, 0x1b, 0x7a, 0xd3, 0x68, 0x9e, 0xe6, 0xbd, 0x99, 0x37,
	0x88, 0xbc, 0xca, 0x0b, 0xa5, 0xd5, 0xb9, 0x88, 0xe4, 0x79, 0x24, 0xb4, 0x08, 0x31, 0xa4, 0x53,
	0x25, 0x55, 0x28, 0xcb, 0x3c, 0x14, 0x91, 0x9c, 0xcf, 0x7a, 0x10, 0x25, 0xa5, 0xca, 0x6a, 0x50,
	0xf0, 0xd3, 0x26, 0xd3, 0x2b, 0xa1, 0x45, 0xaa, 0x1e, 0x3e, 0x67, 0xf7, 0x8a, 0x9e, 0x10, 0xa7,
	0x4a, 0x62, 0x66, 0xf9, 0xd6, 0xe2, 0x90, 0x9b, 0x23, 0x3d, 0x26, 0x76, 0x12, 0x33, 0xdb, 0xb7,
	0x16, 0x2e, 0xb7, 0x93, 0x98, 0x32, 0xb2, 0x1f, 0x15, 0x20, 0x34, 0xc4, 0xcc, 0xf1, 0xad, 0x85,
	0xc3, 0xdb, 0xd0, 0x64, 0xaa, 0x3c, 0xc6, 0x8c, 0x5b, 0x67, 0x9a, 0xb0, 0x7b, 0xa3, 0x0a, 0x36,
	0xc1, 0xca, 0x6d, 0x48, 0xe7, 0xe4, 0x40, 0xe5, 0x50, 0x60, 0xca, 0xc3, 0x54, 0x17, 0x53, 0x4a,
	0xdc, 0x4c, 0x48, 0x60, 0xfb, 0x78, 0x8f, 0x67, 0x3a, 0x23, 0x5e, 0x01, 0x52, 0x14, 0x2b, 0x76,
	0x80, 0xb7, 0x4d, 0x64, 0x74, 0xaf, 0x60, 0xcd, 0x0e, 0x6b, 0xdd, 0x2b, 0x58, 0x9b, 0xd7, 0x7a,
	0x9d, 0x03, 0x23, 0xbe, 0xb5, 0x38, 0xe2, 0x78, 0x36, 0x6c, 0x91, 0xca, 0x22, 0xc8, 0x75, 0xc9,
	0x4e, 0x7d, 0xc7, 0xb0, 0xb5, 0x71, 0xf0, 0x83, 0x1c, 0x71, 0x78, 0x6c, 0x66, 0xb1, 0x8c, 0xe3,
	0x8e, 0xde, 0x1a, 0xa5, 0xb7, 0xc7, 0xe8, 0x9d, 0x67, 0xfa, 0x7e, 0x63, 0xee, 0x76, 0x63, 0x28,
	0x6d, 0xf2, 0x2c, 0x2d, 0x28, 0xc8, 0x09, 0x87, 0x3c, 0x5d, 0xf7, 0xcd, 0x78, 0x43, 0xdc, 0x24,
	0xbb, 0x57, 0xa8, 0x60, 0x7a, 0xc1, 0xc2, 0x9e, 0xa1, 0x61, 0x0f, 0xc7, 0x11, 0x45, 0xdf, 0x12,
	0xaf, 0xd4, 0x42, 0x57, 0x25, 0x6a, 0xdb, 0xc4, 0x63, 0xf1, 0x1b, 0xcc, 0xf3, 0x06, 0x17, 0xfc,
	0xb2, 0x86, 0xa4, 0xd7, 0x49, 0xa9, 0x4d, 0x8b, 0x59, 0x25, 0xef, 0xa0, 0x40, 0xda, 0x09, 0x6f,
	0xa2, 0xff, 0x2f, 0x6f, 0xe4, 0xa7, 0x49, 0xa9, 0x99, 0xe3, 0x3b, 0xbb, 0xe5, 0x1b, 0x54, 0xf0,
	0x1b, 0xc5, 0xb4, 0x06, 0x7c, 0xc3, 0xcd, 0x19, 0x59, 0xc7, 0xd6, 0x15, 0x7b, 0xd4, 0x15, 0x67,
	0xe0, 0xca, 0x2e, 0x0f, 0x1a, 0xc7, 0x26, 0x03, 0xc7, 0xba, 0xe5, 0xf0, 0x86, 0xcb, 0x71, 0xf1,
	0xc7, 0x26, 0xc7, 0x8d, 0xb2, 0x1b, 0x28, 0x9e, 0x92, 0x08, 0xe8, 0x47, 0xe2, 0x2d, 0xe3, 0xf8,
	0x4b, 0x06, 0x74, 0xbe, 0x31, 0x89, 0xde, 0x12, 0xcd, 0xcf, 0xb6, 0xa7, 0xd4, 0x6b, 0x3d, 0xd8,
	0xa3, 0x57, 0xc4, 0xfb, 0x04, 0xda, 0x94, 0xd9, 0x1c, 0xe8, 0x63, 0x05, 0xa5, 0x36, 0xa8, 0x97,
	0x8b, 0x7c, 0x20, 0x87, 0x1c, 0xa4, 0x7a, 0x82, 0xdd, 0x75, 0x66, 0xdb, 0x75, 0x06, 0x2a, 0x96,
	0x69, 0x3a, 0xfe, 0xfa, 0xab, 0x78, 0x80, 0x1d, 0x2a, 0xcc, 0xde, 0x04, 0x7b, 0xf4, 0x9a, 0x90,
	0xda, 0xb6, 0x4b, 0x51, 0x02, 0x3d, 0xfb, 0xc7, 0x54, 0x6a, 0xc8, 0x8b, 0x3d, 0x5d, 0xbe, 0xfe,
	0x7e, 0xda, 0xfd, 0x59, 0xef, 0x95, 0x54, 0xb7, 0xb2, 0xcc, 0x6f, 0x45, 0x24, 0xef, 0x3c, 0xbc,
	0x7e, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0xba, 0x3d, 0xf3, 0x06, 0xf6, 0x04, 0x00, 0x00,
}
