// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/acm/common.proto

package omo_msp_acm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultCode int32

const (
	ResultCode_Success     ResultCode = 0
	ResultCode_MaxLimit    ResultCode = 1
	ResultCode_Repeated    ResultCode = 2
	ResultCode_NotExisted  ResultCode = 3
	ResultCode_DBException ResultCode = 4
	ResultCode_Empty       ResultCode = 5
)

var ResultCode_name = map[int32]string{
	0: "Success",
	1: "MaxLimit",
	2: "Repeated",
	3: "NotExisted",
	4: "DBException",
	5: "Empty",
}

var ResultCode_value = map[string]int32{
	"Success":     0,
	"MaxLimit":    1,
	"Repeated":    2,
	"NotExisted":  3,
	"DBException": 4,
	"Empty":       5,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}

func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e0fbd99cee7f5b8, []int{0}
}

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e0fbd99cee7f5b8, []int{0}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyStatus struct {
	Code                 ResultCode `protobuf:"varint,1,opt,name=code,proto3,enum=omo.msp.acm.ResultCode" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e0fbd99cee7f5b8, []int{1}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_Success
}

func (m *ReplyStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReplyInfo struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               ResultCode `protobuf:"varint,2,opt,name=status,proto3,enum=omo.msp.acm.ResultCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e0fbd99cee7f5b8, []int{2}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetStatus() ResultCode {
	if m != nil {
		return m.Status
	}
	return ResultCode_Success
}

func init() {
	proto.RegisterEnum("omo.msp.acm.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.acm.RequestInfo")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.acm.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.acm.ReplyInfo")
}

func init() {
	proto.RegisterFile("proto/acm/common.proto", fileDescriptor_5e0fbd99cee7f5b8)
}

var fileDescriptor_5e0fbd99cee7f5b8 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xf4, 0xeb, 0x6d, 0x26, 0x52, 0x97, 0x05, 0x6d, 0xf1, 0x24, 0x39, 0x89, 0x42,
	0x02, 0x7a, 0xec, 0xad, 0x9a, 0x83, 0x50, 0x7b, 0x48, 0x6f, 0x5e, 0xca, 0xba, 0x59, 0x25, 0xd0,
	0xc9, 0xac, 0xd9, 0x09, 0xa4, 0xff, 0xbd, 0xec, 0x52, 0xaa, 0x17, 0xbd, 0xcd, 0xf3, 0xe3, 0xf9,
	0x58, 0x16, 0x2e, 0x6d, 0x4b, 0x4c, 0xb9, 0xd2, 0x98, 0x6b, 0x42, 0xa4, 0x26, 0x0b, 0x40, 0x26,
	0x84, 0x94, 0xa1, 0xb3, 0x99, 0xd2, 0x98, 0x2e, 0x21, 0x29, 0xcd, 0x67, 0x67, 0x1c, 0x3f, 0x37,
	0xef, 0x24, 0x05, 0x0c, 0xbb, 0xba, 0x5a, 0x44, 0xd7, 0xd1, 0x4d, 0x5c, 0xfa, 0x53, 0x5e, 0xc1,
	0x94, 0xac, 0x69, 0x15, 0x53, 0xbb, 0x18, 0x04, 0x7c, 0xd2, 0xe9, 0xda, 0x87, 0xed, 0xfe, 0xb0,
	0x65, 0xc5, 0x9d, 0x93, 0x77, 0x30, 0xd2, 0x54, 0x99, 0x90, 0x9e, 0xdd, 0xcf, 0xb3, 0x1f, 0x3b,
	0x59, 0x69, 0x5c, 0xb7, 0xe7, 0x47, 0xaa, 0x4c, 0x19, 0x4c, 0x7e, 0x09, 0xdd, 0xc7, 0xb1, 0xd2,
	0x9f, 0xe9, 0x06, 0xe2, 0xd0, 0xf6, 0xcb, 0x43, 0x72, 0x98, 0xb8, 0xb0, 0x13, 0x32, 0x7f, 0xf4,
	0x1f, 0x6d, 0xb7, 0x0a, 0xe0, 0x9b, 0xca, 0x04, 0xfe, 0x6f, 0x3b, 0xad, 0x8d, 0x73, 0xe2, 0x9f,
	0x3c, 0x83, 0xe9, 0x8b, 0xea, 0xd7, 0x35, 0xd6, 0x2c, 0x22, 0xaf, 0x4a, 0x63, 0x8d, 0x62, 0x53,
	0x89, 0x81, 0x9c, 0x01, 0x6c, 0x88, 0x8b, 0xbe, 0x76, 0x5e, 0x0f, 0xe5, 0x39, 0x24, 0x4f, 0xab,
	0xa2, 0xd7, 0xc6, 0x72, 0x4d, 0x8d, 0x18, 0xc9, 0x18, 0xc6, 0x05, 0x5a, 0x3e, 0x88, 0xf1, 0x6a,
	0xfe, 0x7a, 0x71, 0xfa, 0xe4, 0x25, 0x21, 0xed, 0xd0, 0xd9, 0x9d, 0xd2, 0xf8, 0x36, 0x09, 0xf8,
	0xe1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xe7, 0x81, 0x53, 0x84, 0x01, 0x00, 0x00,
}
