// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/acm/role.proto

package omo_msp_acm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Creator              string   `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Menus                []string `protobuf:"bytes,10,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{0}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RoleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *RoleInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *RoleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *RoleInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RoleInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RoleInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RoleInfo) GetMenus() []string {
	if m != nil {
		return m.Menus
	}
	return nil
}

type ReqRoleAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Menus                []string `protobuf:"bytes,5,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoleAdd) Reset()         { *m = ReqRoleAdd{} }
func (m *ReqRoleAdd) String() string { return proto.CompactTextString(m) }
func (*ReqRoleAdd) ProtoMessage()    {}
func (*ReqRoleAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{1}
}

func (m *ReqRoleAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoleAdd.Unmarshal(m, b)
}
func (m *ReqRoleAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoleAdd.Marshal(b, m, deterministic)
}
func (m *ReqRoleAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoleAdd.Merge(m, src)
}
func (m *ReqRoleAdd) XXX_Size() int {
	return xxx_messageInfo_ReqRoleAdd.Size(m)
}
func (m *ReqRoleAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoleAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoleAdd proto.InternalMessageInfo

func (m *ReqRoleAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRoleAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqRoleAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRoleAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqRoleAdd) GetMenus() []string {
	if m != nil {
		return m.Menus
	}
	return nil
}

type ReplyRoleInfo struct {
	Info                 *RoleInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyRoleInfo) Reset()         { *m = ReplyRoleInfo{} }
func (m *ReplyRoleInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyRoleInfo) ProtoMessage()    {}
func (*ReplyRoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{2}
}

func (m *ReplyRoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRoleInfo.Unmarshal(m, b)
}
func (m *ReplyRoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRoleInfo.Marshal(b, m, deterministic)
}
func (m *ReplyRoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRoleInfo.Merge(m, src)
}
func (m *ReplyRoleInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyRoleInfo.Size(m)
}
func (m *ReplyRoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRoleInfo proto.InternalMessageInfo

func (m *ReplyRoleInfo) GetInfo() *RoleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyRoleInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyRoleList struct {
	Number               int32        `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*RoleInfo  `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyRoleList) Reset()         { *m = ReplyRoleList{} }
func (m *ReplyRoleList) String() string { return proto.CompactTextString(m) }
func (*ReplyRoleList) ProtoMessage()    {}
func (*ReplyRoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{3}
}

func (m *ReplyRoleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRoleList.Unmarshal(m, b)
}
func (m *ReplyRoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRoleList.Marshal(b, m, deterministic)
}
func (m *ReplyRoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRoleList.Merge(m, src)
}
func (m *ReplyRoleList) XXX_Size() int {
	return xxx_messageInfo_ReplyRoleList.Size(m)
}
func (m *ReplyRoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRoleList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRoleList proto.InternalMessageInfo

func (m *ReplyRoleList) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyRoleList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRoleList) GetList() []*RoleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqRoleUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Menus                []string `protobuf:"bytes,5,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoleUpdate) Reset()         { *m = ReqRoleUpdate{} }
func (m *ReqRoleUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqRoleUpdate) ProtoMessage()    {}
func (*ReqRoleUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{4}
}

func (m *ReqRoleUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoleUpdate.Unmarshal(m, b)
}
func (m *ReqRoleUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoleUpdate.Marshal(b, m, deterministic)
}
func (m *ReqRoleUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoleUpdate.Merge(m, src)
}
func (m *ReqRoleUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqRoleUpdate.Size(m)
}
func (m *ReqRoleUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoleUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoleUpdate proto.InternalMessageInfo

func (m *ReqRoleUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqRoleUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRoleUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqRoleUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRoleUpdate) GetMenus() []string {
	if m != nil {
		return m.Menus
	}
	return nil
}

type ReqRoleMenus struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Menus                []string `protobuf:"bytes,3,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoleMenus) Reset()         { *m = ReqRoleMenus{} }
func (m *ReqRoleMenus) String() string { return proto.CompactTextString(m) }
func (*ReqRoleMenus) ProtoMessage()    {}
func (*ReqRoleMenus) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{5}
}

func (m *ReqRoleMenus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoleMenus.Unmarshal(m, b)
}
func (m *ReqRoleMenus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoleMenus.Marshal(b, m, deterministic)
}
func (m *ReqRoleMenus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoleMenus.Merge(m, src)
}
func (m *ReqRoleMenus) XXX_Size() int {
	return xxx_messageInfo_ReqRoleMenus.Size(m)
}
func (m *ReqRoleMenus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoleMenus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoleMenus proto.InternalMessageInfo

func (m *ReqRoleMenus) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ReqRoleMenus) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRoleMenus) GetMenus() []string {
	if m != nil {
		return m.Menus
	}
	return nil
}

type ReplyRoleMenu struct {
	Role                 string       `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Menus                []string     `protobuf:"bytes,3,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyRoleMenu) Reset()         { *m = ReplyRoleMenu{} }
func (m *ReplyRoleMenu) String() string { return proto.CompactTextString(m) }
func (*ReplyRoleMenu) ProtoMessage()    {}
func (*ReplyRoleMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_599166315131034b, []int{6}
}

func (m *ReplyRoleMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRoleMenu.Unmarshal(m, b)
}
func (m *ReplyRoleMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRoleMenu.Marshal(b, m, deterministic)
}
func (m *ReplyRoleMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRoleMenu.Merge(m, src)
}
func (m *ReplyRoleMenu) XXX_Size() int {
	return xxx_messageInfo_ReplyRoleMenu.Size(m)
}
func (m *ReplyRoleMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRoleMenu.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRoleMenu proto.InternalMessageInfo

func (m *ReplyRoleMenu) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ReplyRoleMenu) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRoleMenu) GetMenus() []string {
	if m != nil {
		return m.Menus
	}
	return nil
}

func init() {
	proto.RegisterType((*RoleInfo)(nil), "omo.msp.acm.RoleInfo")
	proto.RegisterType((*ReqRoleAdd)(nil), "omo.msp.acm.ReqRoleAdd")
	proto.RegisterType((*ReplyRoleInfo)(nil), "omo.msp.acm.ReplyRoleInfo")
	proto.RegisterType((*ReplyRoleList)(nil), "omo.msp.acm.ReplyRoleList")
	proto.RegisterType((*ReqRoleUpdate)(nil), "omo.msp.acm.ReqRoleUpdate")
	proto.RegisterType((*ReqRoleMenus)(nil), "omo.msp.acm.ReqRoleMenus")
	proto.RegisterType((*ReplyRoleMenu)(nil), "omo.msp.acm.ReplyRoleMenu")
}

func init() {
	proto.RegisterFile("proto/acm/role.proto", fileDescriptor_599166315131034b)
}

var fileDescriptor_599166315131034b = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x3f, 0xe2, 0x26, 0x93, 0x82, 0xd0, 0xaa, 0x4d, 0x97, 0x9c, 0x22, 0x9f, 0xc2, 0x25,
	0x45, 0xe1, 0xc8, 0xa1, 0xa4, 0x12, 0x54, 0x48, 0x20, 0x90, 0x03, 0x17, 0x2e, 0x95, 0x63, 0x4f,
	0x91, 0x55, 0xaf, 0xd7, 0x5d, 0xdb, 0x45, 0x9c, 0xe0, 0xc0, 0xbf, 0x45, 0xe2, 0x37, 0xa0, 0x9d,
	0xc4, 0xa9, 0xd3, 0xac, 0x5b, 0x55, 0xbd, 0xed, 0xdb, 0x37, 0x79, 0xf3, 0x76, 0xde, 0xc4, 0x70,
	0x90, 0x2b, 0x59, 0xca, 0xe3, 0x30, 0x12, 0xc7, 0x4a, 0xa6, 0x38, 0x25, 0xc8, 0x06, 0x52, 0xc8,
	0xa9, 0x28, 0xf2, 0x69, 0x18, 0x89, 0xd1, 0xf0, 0xa6, 0x24, 0x92, 0x42, 0xc8, 0x6c, 0x55, 0xe4,
	0xff, 0xb3, 0xa0, 0x17, 0xc8, 0x14, 0xdf, 0x67, 0x17, 0x92, 0x3d, 0x03, 0xa7, 0x4a, 0x62, 0x6e,
	0x8d, 0xad, 0x49, 0x3f, 0xd0, 0x47, 0xf6, 0x14, 0xec, 0x24, 0xe6, 0xf6, 0xd8, 0x9a, 0xb8, 0x81,
	0x9d, 0xc4, 0x8c, 0xc3, 0x5e, 0xa4, 0x30, 0x2c, 0x31, 0xe6, 0xce, 0xd8, 0x9a, 0x38, 0x41, 0x0d,
	0x35, 0x53, 0xe5, 0x31, 0x31, 0xee, 0x8a, 0x59, 0x43, 0xc6, 0xc0, 0xcd, 0x42, 0x81, 0xbc, 0x4b,
	0xb2, 0x74, 0x66, 0x43, 0xf0, 0x14, 0x8a, 0x50, 0x5d, 0x72, 0x8f, 0x6e, 0xd7, 0x68, 0xa3, 0x2f,
	0x15, 0xdf, 0x23, 0xa2, 0x86, 0x6c, 0x04, 0x3d, 0x99, 0xa3, 0x22, 0xaa, 0x47, 0xd4, 0x06, 0xb3,
	0x03, 0xe8, 0xca, 0x1f, 0x19, 0x2a, 0xde, 0x27, 0x62, 0x05, 0xf4, 0xad, 0xc0, 0xac, 0x2a, 0x38,
	0x8c, 0x1d, 0x7d, 0x4b, 0xc0, 0xff, 0x6d, 0x01, 0x04, 0x78, 0xa5, 0xdf, 0x3c, 0x8f, 0x6f, 0xcc,
	0x59, 0x46, 0x73, 0xf6, 0x96, 0xb9, 0xa6, 0x05, 0xa7, 0xcd, 0x82, 0x6b, 0xb4, 0xd0, 0x6d, 0x5a,
	0x48, 0xe1, 0x49, 0x80, 0x79, 0xfa, 0x73, 0x33, 0xf7, 0x17, 0xe0, 0x26, 0xd9, 0x85, 0x24, 0x13,
	0x83, 0xd9, 0xe1, 0xb4, 0x11, 0xdc, 0xb4, 0x2e, 0x0a, 0xa8, 0x84, 0xbd, 0x04, 0xaf, 0x28, 0xc3,
	0xb2, 0x2a, 0xc8, 0xdb, 0x60, 0xc6, 0xb7, 0x8b, 0xb5, 0xec, 0x82, 0xf8, 0x60, 0x5d, 0xe7, 0xff,
	0xb1, 0x1a, 0xed, 0x3e, 0x24, 0x45, 0xa9, 0xdf, 0x97, 0x55, 0x62, 0x89, 0x8a, 0x1a, 0x76, 0x83,
	0x35, 0x7a, 0xb8, 0xb6, 0x36, 0x9e, 0x26, 0x45, 0xc9, 0x9d, 0xb1, 0x73, 0x87, 0x71, 0x5d, 0xe2,
	0xff, 0xd2, 0x2e, 0x68, 0xec, 0x5f, 0x69, 0x2f, 0x0c, 0xcb, 0x56, 0x67, 0x61, 0x1b, 0xb3, 0x70,
	0x5a, 0xb3, 0x70, 0x77, 0xb3, 0x30, 0x4c, 0xfd, 0x0b, 0xec, 0xaf, 0x0d, 0x7c, 0xd4, 0x58, 0x77,
	0xd3, 0x7f, 0x96, 0x3a, 0x79, 0x7d, 0xde, 0x52, 0xb5, 0xdb, 0x54, 0x9d, 0xa6, 0xea, 0x65, 0x63,
	0xb8, 0x5a, 0xd7, 0x28, 0xfb, 0xf0, 0xc1, 0x1a, 0x9b, 0xcd, 0xfe, 0x3a, 0x30, 0xd0, 0x8d, 0x16,
	0xa8, 0xae, 0x93, 0x08, 0xd9, 0x09, 0x78, 0xf3, 0x38, 0xfe, 0x94, 0x21, 0x3b, 0xba, 0xa5, 0x58,
	0xef, 0xf7, 0x68, 0xb4, 0xdb, 0xaa, 0x0e, 0xc6, 0xef, 0xb0, 0x37, 0xe0, 0x9d, 0x61, 0xa9, 0x05,
	0x6e, 0x5b, 0xba, 0xaa, 0xb0, 0x28, 0x75, 0xd5, 0x3d, 0x0a, 0x27, 0xd0, 0x0f, 0x50, 0xc8, 0x6b,
	0xbc, 0x5b, 0x64, 0xb8, 0x2b, 0xb2, 0x65, 0x61, 0x9e, 0xa6, 0xe6, 0x5f, 0x7f, 0x0e, 0xbf, 0x63,
	0x9b, 0x05, 0xbd, 0xcc, 0x7e, 0x87, 0xbd, 0x03, 0x58, 0xad, 0xd4, 0x69, 0x58, 0x20, 0x1b, 0x99,
	0x26, 0xb1, 0xe2, 0xef, 0x79, 0xca, 0x5b, 0x80, 0x79, 0x9e, 0x63, 0x16, 0x53, 0x8e, 0xcf, 0x4d,
	0x3a, 0xb4, 0x39, 0x6d, 0x32, 0x9a, 0xf4, 0x3b, 0xec, 0x0c, 0xf6, 0x17, 0xd5, 0xb2, 0x54, 0x61,
	0x54, 0x3e, 0x4a, 0xe8, 0xf4, 0xe8, 0xdb, 0xe1, 0xe6, 0xa3, 0xfd, 0x5a, 0x0a, 0x79, 0x2e, 0x8a,
	0xfc, 0x3c, 0x8c, 0xc4, 0xd2, 0xa3, 0xeb, 0x57, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x99,
	0xb6, 0x3b, 0xf7, 0x05, 0x00, 0x00,
}
