// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/acm/user.proto

package omo_msp_acm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLink struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	User                 string   `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	Type                 uint32   `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	Owner                string   `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Status               uint32   `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Roles                []string `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles,omitempty"`
	Links                []string `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLink) Reset()         { *m = UserLink{} }
func (m *UserLink) String() string { return proto.CompactTextString(m) }
func (*UserLink) ProtoMessage()    {}
func (*UserLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{0}
}

func (m *UserLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLink.Unmarshal(m, b)
}
func (m *UserLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLink.Marshal(b, m, deterministic)
}
func (m *UserLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLink.Merge(m, src)
}
func (m *UserLink) XXX_Size() int {
	return xxx_messageInfo_UserLink.Size(m)
}
func (m *UserLink) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLink.DiscardUnknown(m)
}

var xxx_messageInfo_UserLink proto.InternalMessageInfo

func (m *UserLink) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserLink) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserLink) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *UserLink) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UserLink) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *UserLink) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *UserLink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserLink) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserLink) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UserLink) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UserLink) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserLink) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *UserLink) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

type ReqUserAdd struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Roles                []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Links                []string `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserAdd) Reset()         { *m = ReqUserAdd{} }
func (m *ReqUserAdd) String() string { return proto.CompactTextString(m) }
func (*ReqUserAdd) ProtoMessage()    {}
func (*ReqUserAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{1}
}

func (m *ReqUserAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserAdd.Unmarshal(m, b)
}
func (m *ReqUserAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserAdd.Marshal(b, m, deterministic)
}
func (m *ReqUserAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserAdd.Merge(m, src)
}
func (m *ReqUserAdd) XXX_Size() int {
	return xxx_messageInfo_ReqUserAdd.Size(m)
}
func (m *ReqUserAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserAdd proto.InternalMessageInfo

func (m *ReqUserAdd) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqUserAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqUserAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUserAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqUserAdd) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ReqUserAdd) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

type ReplyUserLink struct {
	Info                 *UserLink    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyUserLink) Reset()         { *m = ReplyUserLink{} }
func (m *ReplyUserLink) String() string { return proto.CompactTextString(m) }
func (*ReplyUserLink) ProtoMessage()    {}
func (*ReplyUserLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{2}
}

func (m *ReplyUserLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserLink.Unmarshal(m, b)
}
func (m *ReplyUserLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserLink.Marshal(b, m, deterministic)
}
func (m *ReplyUserLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserLink.Merge(m, src)
}
func (m *ReplyUserLink) XXX_Size() int {
	return xxx_messageInfo_ReplyUserLink.Size(m)
}
func (m *ReplyUserLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserLink.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserLink proto.InternalMessageInfo

func (m *ReplyUserLink) GetInfo() *UserLink {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyUserLink) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqUserStatus struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserStatus) Reset()         { *m = ReqUserStatus{} }
func (m *ReqUserStatus) String() string { return proto.CompactTextString(m) }
func (*ReqUserStatus) ProtoMessage()    {}
func (*ReqUserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{3}
}

func (m *ReqUserStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserStatus.Unmarshal(m, b)
}
func (m *ReqUserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserStatus.Marshal(b, m, deterministic)
}
func (m *ReqUserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserStatus.Merge(m, src)
}
func (m *ReqUserStatus) XXX_Size() int {
	return xxx_messageInfo_ReqUserStatus.Size(m)
}
func (m *ReqUserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserStatus proto.InternalMessageInfo

func (m *ReqUserStatus) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserStatus) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqUserStatus) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUserStatus) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReplyUserList struct {
	Total                uint64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageNow              uint32      `protobuf:"varint,2,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	PageMax              uint32      `protobuf:"varint,3,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	Users                []*UserLink `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReplyUserList) Reset()         { *m = ReplyUserList{} }
func (m *ReplyUserList) String() string { return proto.CompactTextString(m) }
func (*ReplyUserList) ProtoMessage()    {}
func (*ReplyUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{4}
}

func (m *ReplyUserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserList.Unmarshal(m, b)
}
func (m *ReplyUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserList.Marshal(b, m, deterministic)
}
func (m *ReplyUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserList.Merge(m, src)
}
func (m *ReplyUserList) XXX_Size() int {
	return xxx_messageInfo_ReplyUserList.Size(m)
}
func (m *ReplyUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserList proto.InternalMessageInfo

func (m *ReplyUserList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyUserList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyUserList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyUserList) GetUsers() []*UserLink {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReplyUserPermission struct {
	User                 string       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Permission           bool         `protobuf:"varint,2,opt,name=permission,proto3" json:"permission,omitempty"`
	Owner                string       `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyUserPermission) Reset()         { *m = ReplyUserPermission{} }
func (m *ReplyUserPermission) String() string { return proto.CompactTextString(m) }
func (*ReplyUserPermission) ProtoMessage()    {}
func (*ReplyUserPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{5}
}

func (m *ReplyUserPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserPermission.Unmarshal(m, b)
}
func (m *ReplyUserPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserPermission.Marshal(b, m, deterministic)
}
func (m *ReplyUserPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserPermission.Merge(m, src)
}
func (m *ReplyUserPermission) XXX_Size() int {
	return xxx_messageInfo_ReplyUserPermission.Size(m)
}
func (m *ReplyUserPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserPermission.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserPermission proto.InternalMessageInfo

func (m *ReplyUserPermission) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReplyUserPermission) GetPermission() bool {
	if m != nil {
		return m.Permission
	}
	return false
}

func (m *ReplyUserPermission) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyUserPermission) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqUserPermission struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserPermission) Reset()         { *m = ReqUserPermission{} }
func (m *ReqUserPermission) String() string { return proto.CompactTextString(m) }
func (*ReqUserPermission) ProtoMessage()    {}
func (*ReqUserPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{6}
}

func (m *ReqUserPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserPermission.Unmarshal(m, b)
}
func (m *ReqUserPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserPermission.Marshal(b, m, deterministic)
}
func (m *ReqUserPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserPermission.Merge(m, src)
}
func (m *ReqUserPermission) XXX_Size() int {
	return xxx_messageInfo_ReqUserPermission.Size(m)
}
func (m *ReqUserPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserPermission.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserPermission proto.InternalMessageInfo

func (m *ReqUserPermission) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqUserPermission) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReqUserPermission) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ReqUserPermission) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReqUserLinks struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	List                 []string `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserLinks) Reset()         { *m = ReqUserLinks{} }
func (m *ReqUserLinks) String() string { return proto.CompactTextString(m) }
func (*ReqUserLinks) ProtoMessage()    {}
func (*ReqUserLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{7}
}

func (m *ReqUserLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserLinks.Unmarshal(m, b)
}
func (m *ReqUserLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserLinks.Marshal(b, m, deterministic)
}
func (m *ReqUserLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserLinks.Merge(m, src)
}
func (m *ReqUserLinks) XXX_Size() int {
	return xxx_messageInfo_ReqUserLinks.Size(m)
}
func (m *ReqUserLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserLinks.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserLinks proto.InternalMessageInfo

func (m *ReqUserLinks) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserLinks) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqUserLinks) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUserLinks) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqUserLinks) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyUserLinks struct {
	User                 string       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	List                 []string     `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyUserLinks) Reset()         { *m = ReplyUserLinks{} }
func (m *ReplyUserLinks) String() string { return proto.CompactTextString(m) }
func (*ReplyUserLinks) ProtoMessage()    {}
func (*ReplyUserLinks) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b19b61bebab524, []int{8}
}

func (m *ReplyUserLinks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserLinks.Unmarshal(m, b)
}
func (m *ReplyUserLinks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserLinks.Marshal(b, m, deterministic)
}
func (m *ReplyUserLinks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserLinks.Merge(m, src)
}
func (m *ReplyUserLinks) XXX_Size() int {
	return xxx_messageInfo_ReplyUserLinks.Size(m)
}
func (m *ReplyUserLinks) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserLinks.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserLinks proto.InternalMessageInfo

func (m *ReplyUserLinks) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReplyUserLinks) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyUserLinks) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLink)(nil), "omo.msp.acm.UserLink")
	proto.RegisterType((*ReqUserAdd)(nil), "omo.msp.acm.ReqUserAdd")
	proto.RegisterType((*ReplyUserLink)(nil), "omo.msp.acm.ReplyUserLink")
	proto.RegisterType((*ReqUserStatus)(nil), "omo.msp.acm.ReqUserStatus")
	proto.RegisterType((*ReplyUserList)(nil), "omo.msp.acm.ReplyUserList")
	proto.RegisterType((*ReplyUserPermission)(nil), "omo.msp.acm.ReplyUserPermission")
	proto.RegisterType((*ReqUserPermission)(nil), "omo.msp.acm.ReqUserPermission")
	proto.RegisterType((*ReqUserLinks)(nil), "omo.msp.acm.ReqUserLinks")
	proto.RegisterType((*ReplyUserLinks)(nil), "omo.msp.acm.ReplyUserLinks")
}

func init() {
	proto.RegisterFile("proto/acm/user.proto", fileDescriptor_39b19b61bebab524)
}

var fileDescriptor_39b19b61bebab524 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x8e, 0x7f, 0x12, 0x92, 0x49, 0x40, 0xe7, 0xec, 0x81, 0xb0, 0xc7, 0x95, 0x90, 0xe5, 0xab,
	0x54, 0x95, 0x42, 0x45, 0x2f, 0x7b, 0x41, 0xa9, 0x2a, 0x21, 0xa4, 0xd2, 0x22, 0x57, 0xdc, 0xf4,
	0x06, 0x6d, 0xed, 0x85, 0xba, 0xc4, 0x5e, 0xe3, 0xdd, 0xf0, 0xd3, 0x07, 0xe8, 0x7d, 0xfb, 0x1c,
	0x7d, 0x88, 0x3e, 0x5a, 0xb5, 0xe3, 0xdf, 0x80, 0x03, 0xa5, 0x77, 0xfb, 0xcd, 0x7c, 0xf9, 0xe6,
	0xdb, 0x99, 0xc9, 0x1a, 0xd6, 0xd3, 0x4c, 0x28, 0xb1, 0xcd, 0x82, 0x78, 0x7b, 0x2e, 0x79, 0x36,
	0x45, 0x48, 0x86, 0x22, 0x16, 0xd3, 0x58, 0xa6, 0x53, 0x16, 0xc4, 0xce, 0xb8, 0xa6, 0x04, 0x22,
	0x8e, 0x45, 0x92, 0x93, 0xbc, 0x9f, 0x26, 0xf4, 0x8f, 0x25, 0xcf, 0xde, 0x46, 0xc9, 0x39, 0xf9,
	0x07, 0xac, 0x79, 0x14, 0x52, 0xc3, 0x35, 0x26, 0x03, 0x5f, 0x1f, 0xc9, 0x1a, 0x98, 0x51, 0x48,
	0x4d, 0xd7, 0x98, 0xd8, 0xbe, 0x19, 0x85, 0x84, 0xc2, 0x4a, 0x90, 0x71, 0xa6, 0x78, 0x48, 0x2d,
	0xd7, 0x98, 0x58, 0x7e, 0x09, 0x75, 0x66, 0x9e, 0x86, 0x98, 0xb1, 0xf3, 0x4c, 0x01, 0xab, 0xdf,
	0x88, 0x8c, 0x76, 0x51, 0xb9, 0x84, 0xc4, 0x81, 0xbe, 0x48, 0x79, 0x86, 0xa9, 0x1e, 0xa6, 0x2a,
	0x4c, 0x08, 0xd8, 0x09, 0x8b, 0x39, 0x5d, 0xc1, 0x38, 0x9e, 0x75, 0x4c, 0xdf, 0x8f, 0xf6, 0xf3,
	0x98, 0x3e, 0xeb, 0x98, 0xba, 0x49, 0x39, 0x1d, 0xb8, 0xc6, 0x64, 0xd5, 0xc7, 0x33, 0x59, 0x87,
	0xae, 0xb8, 0x4a, 0x78, 0x46, 0x01, 0x89, 0x39, 0x20, 0x63, 0xe8, 0x49, 0xc5, 0xd4, 0x5c, 0xd2,
	0x21, 0x72, 0x0b, 0xa4, 0xd9, 0x99, 0x98, 0x71, 0x49, 0x47, 0xae, 0xa5, 0xd9, 0x08, 0x74, 0x74,
	0x16, 0x25, 0xe7, 0x92, 0xae, 0xe6, 0x51, 0x04, 0xde, 0x0f, 0x03, 0xc0, 0xe7, 0x17, 0xba, 0x63,
	0x7b, 0x61, 0x58, 0x19, 0x32, 0x5a, 0x0c, 0x99, 0x0d, 0x43, 0xcd, 0x8b, 0x5a, 0xb7, 0x2e, 0x5a,
	0x99, 0xb5, 0x9b, 0x66, 0x2b, 0x53, 0xdd, 0x56, 0x53, 0xbd, 0xa6, 0xa9, 0x19, 0xac, 0xfa, 0x3c,
	0x9d, 0xdd, 0x54, 0x73, 0x7c, 0x0a, 0x76, 0x94, 0x9c, 0x0a, 0xb4, 0x35, 0xdc, 0xd9, 0x98, 0x36,
	0x16, 0x61, 0x5a, 0x92, 0x7c, 0xa4, 0x90, 0xe7, 0x55, 0x53, 0x4c, 0x24, 0xd3, 0x05, 0x32, 0xca,
	0x7e, 0xc0, 0x7c, 0xd9, 0x2e, 0xef, 0x5c, 0x57, 0xc3, 0x0e, 0xe4, 0x89, 0x96, 0xad, 0x19, 0x2f,
	0x88, 0xd6, 0x9d, 0x7e, 0x74, 0x1b, 0xbc, 0x6f, 0xc6, 0xc2, 0xdd, 0xa4, 0xd2, 0x3c, 0x25, 0x14,
	0x9b, 0x61, 0x3d, 0xdb, 0xcf, 0x81, 0xde, 0xb1, 0x94, 0x9d, 0xf1, 0x77, 0xe2, 0xaa, 0x28, 0x59,
	0xc2, 0x32, 0x73, 0xc8, 0xae, 0xb1, 0x64, 0x91, 0x39, 0x64, 0xd7, 0xe4, 0x19, 0x74, 0xf5, 0xc0,
	0x24, 0xb5, 0x5d, 0x6b, 0x79, 0x9b, 0x72, 0x8e, 0xf7, 0xdd, 0x80, 0xff, 0x2a, 0x23, 0x47, 0x3c,
	0x8b, 0x23, 0x29, 0x23, 0x91, 0xb4, 0x6e, 0xc0, 0x16, 0x40, 0x5a, 0x31, 0xd0, 0x4f, 0xdf, 0x6f,
	0x44, 0xea, 0xab, 0x5a, 0xcd, 0x89, 0xd7, 0x93, 0xb0, 0xff, 0x70, 0x12, 0x11, 0xfc, 0x5b, 0x4c,
	0xe2, 0x01, 0x43, 0x04, 0xec, 0x94, 0xa9, 0xcf, 0x68, 0x65, 0xe0, 0xe3, 0x59, 0xcf, 0x88, 0x05,
	0x4a, 0x1b, 0xcc, 0x5d, 0x14, 0x68, 0xc9, 0x1c, 0xbe, 0xc2, 0xa8, 0x28, 0xa5, 0x9b, 0xd2, 0x36,
	0xf3, 0xb2, 0xae, 0xd9, 0xa8, 0xfb, 0xf8, 0xb5, 0x27, 0x60, 0xcf, 0x22, 0xa9, 0x8a, 0xad, 0xc7,
	0xb3, 0xf7, 0x05, 0xd6, 0x16, 0xd6, 0x5b, 0xb6, 0xde, 0xf1, 0xd1, 0x8b, 0x5c, 0xd5, 0xb2, 0xea,
	0x5a, 0x3b, 0xbf, 0x6c, 0x18, 0xe2, 0x6a, 0xf3, 0xec, 0x32, 0x0a, 0x38, 0xd9, 0x85, 0xde, 0x5e,
	0x18, 0xbe, 0x4f, 0x38, 0xd9, 0xbc, 0xa5, 0x57, 0xbe, 0x01, 0x8e, 0x73, 0xb7, 0x50, 0xe9, 0xd4,
	0xeb, 0x90, 0x57, 0xd0, 0xdb, 0xe7, 0x4a, 0x0b, 0xdc, 0x36, 0x74, 0x31, 0xe7, 0x52, 0x1d, 0x24,
	0xa7, 0xe2, 0x01, 0x85, 0x5d, 0x18, 0xf8, 0x3c, 0x16, 0x97, 0xfc, 0x7e, 0x91, 0xf1, 0x5d, 0x11,
	0x1d, 0xf7, 0x3a, 0x64, 0x0f, 0x56, 0xf6, 0xb9, 0xc2, 0x3f, 0x4f, 0xeb, 0xcf, 0x8f, 0xd8, 0x19,
	0x5f, 0xee, 0x41, 0x2a, 0xaf, 0x43, 0x7c, 0x18, 0x1d, 0xc8, 0xc6, 0x92, 0x6d, 0xb5, 0x35, 0xa3,
	0xce, 0x3b, 0x6e, 0xbb, 0x5a, 0xcd, 0xf0, 0x3a, 0x64, 0x1f, 0x86, 0xc7, 0xf8, 0x85, 0xf0, 0xf1,
	0x69, 0xfb, 0xbf, 0x4d, 0x12, 0xc7, 0xed, 0x3c, 0x59, 0xde, 0x1f, 0xe9, 0x75, 0xc8, 0x1b, 0x18,
	0xe5, 0x42, 0xc5, 0x7b, 0xe4, 0xb4, 0x29, 0xe5, 0xb9, 0x7b, 0xba, 0x54, 0xd9, 0xc9, 0x57, 0xec,
	0xaf, 0xed, 0xbc, 0xde, 0xfc, 0xb8, 0x51, 0x7d, 0x6b, 0x5f, 0x8a, 0x58, 0x9c, 0xc4, 0x32, 0x3d,
	0x61, 0x41, 0xfc, 0xa9, 0x87, 0xe1, 0x17, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x06, 0x20,
	0x3a, 0xae, 0x07, 0x00, 0x00,
}
