// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/acm/user.proto

package omo_msp_acm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	AddOne(ctx context.Context, in *ReqUserAdd, opts ...client.CallOption) (*ReplyUserLink, error)
	GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyUserLink, error)
	RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error)
	GetList(ctx context.Context, in *ReqUserList, opts ...client.CallOption) (*ReplyUserList, error)
	IsPermission(ctx context.Context, in *ReqUserPermission, opts ...client.CallOption) (*ReplyUserPermission, error)
	UpdateRoles(ctx context.Context, in *ReqUserLinks, opts ...client.CallOption) (*ReplyUserLinks, error)
	UpdateLinks(ctx context.Context, in *ReqUserLinks, opts ...client.CallOption) (*ReplyUserLinks, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) AddOne(ctx context.Context, in *ReqUserAdd, opts ...client.CallOption) (*ReplyUserLink, error) {
	req := c.c.NewRequest(c.name, "UserService.AddOne", in)
	out := new(ReplyUserLink)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyUserLink, error) {
	req := c.c.NewRequest(c.name, "UserService.GetOne", in)
	out := new(ReplyUserLink)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "UserService.RemoveOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetList(ctx context.Context, in *ReqUserList, opts ...client.CallOption) (*ReplyUserList, error) {
	req := c.c.NewRequest(c.name, "UserService.GetList", in)
	out := new(ReplyUserList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) IsPermission(ctx context.Context, in *ReqUserPermission, opts ...client.CallOption) (*ReplyUserPermission, error) {
	req := c.c.NewRequest(c.name, "UserService.IsPermission", in)
	out := new(ReplyUserPermission)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateRoles(ctx context.Context, in *ReqUserLinks, opts ...client.CallOption) (*ReplyUserLinks, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateRoles", in)
	out := new(ReplyUserLinks)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateLinks(ctx context.Context, in *ReqUserLinks, opts ...client.CallOption) (*ReplyUserLinks, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateLinks", in)
	out := new(ReplyUserLinks)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	AddOne(context.Context, *ReqUserAdd, *ReplyUserLink) error
	GetOne(context.Context, *RequestInfo, *ReplyUserLink) error
	RemoveOne(context.Context, *RequestInfo, *ReplyInfo) error
	GetList(context.Context, *ReqUserList, *ReplyUserList) error
	IsPermission(context.Context, *ReqUserPermission, *ReplyUserPermission) error
	UpdateRoles(context.Context, *ReqUserLinks, *ReplyUserLinks) error
	UpdateLinks(context.Context, *ReqUserLinks, *ReplyUserLinks) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		AddOne(ctx context.Context, in *ReqUserAdd, out *ReplyUserLink) error
		GetOne(ctx context.Context, in *RequestInfo, out *ReplyUserLink) error
		RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error
		GetList(ctx context.Context, in *ReqUserList, out *ReplyUserList) error
		IsPermission(ctx context.Context, in *ReqUserPermission, out *ReplyUserPermission) error
		UpdateRoles(ctx context.Context, in *ReqUserLinks, out *ReplyUserLinks) error
		UpdateLinks(ctx context.Context, in *ReqUserLinks, out *ReplyUserLinks) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) AddOne(ctx context.Context, in *ReqUserAdd, out *ReplyUserLink) error {
	return h.UserServiceHandler.AddOne(ctx, in, out)
}

func (h *userServiceHandler) GetOne(ctx context.Context, in *RequestInfo, out *ReplyUserLink) error {
	return h.UserServiceHandler.GetOne(ctx, in, out)
}

func (h *userServiceHandler) RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error {
	return h.UserServiceHandler.RemoveOne(ctx, in, out)
}

func (h *userServiceHandler) GetList(ctx context.Context, in *ReqUserList, out *ReplyUserList) error {
	return h.UserServiceHandler.GetList(ctx, in, out)
}

func (h *userServiceHandler) IsPermission(ctx context.Context, in *ReqUserPermission, out *ReplyUserPermission) error {
	return h.UserServiceHandler.IsPermission(ctx, in, out)
}

func (h *userServiceHandler) UpdateRoles(ctx context.Context, in *ReqUserLinks, out *ReplyUserLinks) error {
	return h.UserServiceHandler.UpdateRoles(ctx, in, out)
}

func (h *userServiceHandler) UpdateLinks(ctx context.Context, in *ReqUserLinks, out *ReplyUserLinks) error {
	return h.UserServiceHandler.UpdateLinks(ctx, in, out)
}
